name: Build+Test+Deploy

on:
  workflow_dispatch:
  pull_request:
  push:
    branches:
      - master

jobs:
  default:
    name: Build + Test + Deploy Website
    runs-on: ubuntu-latest
    container: ros:noetic-ros-base
    steps:
    - uses: actions/checkout@v2
    - name: "Install ruby"
      run: |
        apt-get update -q
        apt-get install -q -y ruby-dev libffi-dev build-essential git
    - name: "Run htmlproofer.sh"
      run: ./htmlproofer.sh
    - name: Deploy
      if: ${{ success() && github.event_name == 'push'}}
      uses: peaceiris/actions-gh-pages@v3
      with:
        github_token: ${{ secrets.GITHUB_TOKEN }}
        publish_dir: ./build/html
        force_orphan: true
