// Generated by gencpp from file gripper_action/gripperMoveActionGoal.msg
// DO NOT EDIT!


#ifndef GRIPPER_ACTION_MESSAGE_GRIPPERMOVEACTIONGOAL_H
#define GRIPPER_ACTION_MESSAGE_GRIPPERMOVEACTIONGOAL_H


#include <string>
#include <vector>
#include <memory>

#include <ros/types.h>
#include <ros/serialization.h>
#include <ros/builtin_message_traits.h>
#include <ros/message_operations.h>

#include <std_msgs/Header.h>
#include <actionlib_msgs/GoalID.h>
#include <gripper_action/gripperMoveGoal.h>

namespace gripper_action
{
template <class ContainerAllocator>
struct gripperMoveActionGoal_
{
  typedef gripperMoveActionGoal_<ContainerAllocator> Type;

  gripperMoveActionGoal_()
    : header()
    , goal_id()
    , goal()  {
    }
  gripperMoveActionGoal_(const ContainerAllocator& _alloc)
    : header(_alloc)
    , goal_id(_alloc)
    , goal(_alloc)  {
  (void)_alloc;
    }



   typedef  ::std_msgs::Header_<ContainerAllocator>  _header_type;
  _header_type header;

   typedef  ::actionlib_msgs::GoalID_<ContainerAllocator>  _goal_id_type;
  _goal_id_type goal_id;

   typedef  ::gripper_action::gripperMoveGoal_<ContainerAllocator>  _goal_type;
  _goal_type goal;





  typedef boost::shared_ptr< ::gripper_action::gripperMoveActionGoal_<ContainerAllocator> > Ptr;
  typedef boost::shared_ptr< ::gripper_action::gripperMoveActionGoal_<ContainerAllocator> const> ConstPtr;

}; // struct gripperMoveActionGoal_

typedef ::gripper_action::gripperMoveActionGoal_<std::allocator<void> > gripperMoveActionGoal;

typedef boost::shared_ptr< ::gripper_action::gripperMoveActionGoal > gripperMoveActionGoalPtr;
typedef boost::shared_ptr< ::gripper_action::gripperMoveActionGoal const> gripperMoveActionGoalConstPtr;

// constants requiring out of line definition



template<typename ContainerAllocator>
std::ostream& operator<<(std::ostream& s, const ::gripper_action::gripperMoveActionGoal_<ContainerAllocator> & v)
{
ros::message_operations::Printer< ::gripper_action::gripperMoveActionGoal_<ContainerAllocator> >::stream(s, "", v);
return s;
}


template<typename ContainerAllocator1, typename ContainerAllocator2>
bool operator==(const ::gripper_action::gripperMoveActionGoal_<ContainerAllocator1> & lhs, const ::gripper_action::gripperMoveActionGoal_<ContainerAllocator2> & rhs)
{
  return lhs.header == rhs.header &&
    lhs.goal_id == rhs.goal_id &&
    lhs.goal == rhs.goal;
}

template<typename ContainerAllocator1, typename ContainerAllocator2>
bool operator!=(const ::gripper_action::gripperMoveActionGoal_<ContainerAllocator1> & lhs, const ::gripper_action::gripperMoveActionGoal_<ContainerAllocator2> & rhs)
{
  return !(lhs == rhs);
}


} // namespace gripper_action

namespace ros
{
namespace message_traits
{





template <class ContainerAllocator>
struct IsMessage< ::gripper_action::gripperMoveActionGoal_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsMessage< ::gripper_action::gripperMoveActionGoal_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct IsFixedSize< ::gripper_action::gripperMoveActionGoal_<ContainerAllocator> >
  : FalseType
  { };

template <class ContainerAllocator>
struct IsFixedSize< ::gripper_action::gripperMoveActionGoal_<ContainerAllocator> const>
  : FalseType
  { };

template <class ContainerAllocator>
struct HasHeader< ::gripper_action::gripperMoveActionGoal_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct HasHeader< ::gripper_action::gripperMoveActionGoal_<ContainerAllocator> const>
  : TrueType
  { };


template<class ContainerAllocator>
struct MD5Sum< ::gripper_action::gripperMoveActionGoal_<ContainerAllocator> >
{
  static const char* value()
  {
    return "18ce03fd39ef38d11c4e72f15788bb05";
  }

  static const char* value(const ::gripper_action::gripperMoveActionGoal_<ContainerAllocator>&) { return value(); }
  static const uint64_t static_value1 = 0x18ce03fd39ef38d1ULL;
  static const uint64_t static_value2 = 0x1c4e72f15788bb05ULL;
};

template<class ContainerAllocator>
struct DataType< ::gripper_action::gripperMoveActionGoal_<ContainerAllocator> >
{
  static const char* value()
  {
    return "gripper_action/gripperMoveActionGoal";
  }

  static const char* value(const ::gripper_action::gripperMoveActionGoal_<ContainerAllocator>&) { return value(); }
};

template<class ContainerAllocator>
struct Definition< ::gripper_action::gripperMoveActionGoal_<ContainerAllocator> >
{
  static const char* value()
  {
    return "# ====== DO NOT MODIFY! AUTOGENERATED FROM AN ACTION DEFINITION ======\n"
"\n"
"Header header\n"
"actionlib_msgs/GoalID goal_id\n"
"gripperMoveGoal goal\n"
"\n"
"================================================================================\n"
"MSG: std_msgs/Header\n"
"# Standard metadata for higher-level stamped data types.\n"
"# This is generally used to communicate timestamped data \n"
"# in a particular coordinate frame.\n"
"# \n"
"# sequence ID: consecutively increasing ID \n"
"uint32 seq\n"
"#Two-integer timestamp that is expressed as:\n"
"# * stamp.sec: seconds (stamp_secs) since epoch (in Python the variable is called 'secs')\n"
"# * stamp.nsec: nanoseconds since stamp_secs (in Python the variable is called 'nsecs')\n"
"# time-handling sugar is provided by the client library\n"
"time stamp\n"
"#Frame this data is associated with\n"
"string frame_id\n"
"\n"
"================================================================================\n"
"MSG: actionlib_msgs/GoalID\n"
"# The stamp should store the time at which this goal was requested.\n"
"# It is used by an action server when it tries to preempt all\n"
"# goals that were requested before a certain time\n"
"time stamp\n"
"\n"
"# The id provides a way to associate feedback and\n"
"# result message with specific goal requests. The id\n"
"# specified must be unique.\n"
"string id\n"
"\n"
"\n"
"================================================================================\n"
"MSG: gripper_action/gripperMoveGoal\n"
"# ====== DO NOT MODIFY! AUTOGENERATED FROM AN ACTION DEFINITION ======\n"
"float32 width # [mm]\n"
"int32 speed \n"
"int32 force \n"
"int32 type\n"
;
  }

  static const char* value(const ::gripper_action::gripperMoveActionGoal_<ContainerAllocator>&) { return value(); }
};

} // namespace message_traits
} // namespace ros

namespace ros
{
namespace serialization
{

  template<class ContainerAllocator> struct Serializer< ::gripper_action::gripperMoveActionGoal_<ContainerAllocator> >
  {
    template<typename Stream, typename T> inline static void allInOne(Stream& stream, T m)
    {
      stream.next(m.header);
      stream.next(m.goal_id);
      stream.next(m.goal);
    }

    ROS_DECLARE_ALLINONE_SERIALIZER
  }; // struct gripperMoveActionGoal_

} // namespace serialization
} // namespace ros

namespace ros
{
namespace message_operations
{

template<class ContainerAllocator>
struct Printer< ::gripper_action::gripperMoveActionGoal_<ContainerAllocator> >
{
  template<typename Stream> static void stream(Stream& s, const std::string& indent, const ::gripper_action::gripperMoveActionGoal_<ContainerAllocator>& v)
  {
    s << indent << "header: ";
    s << std::endl;
    Printer< ::std_msgs::Header_<ContainerAllocator> >::stream(s, indent + "  ", v.header);
    s << indent << "goal_id: ";
    s << std::endl;
    Printer< ::actionlib_msgs::GoalID_<ContainerAllocator> >::stream(s, indent + "  ", v.goal_id);
    s << indent << "goal: ";
    s << std::endl;
    Printer< ::gripper_action::gripperMoveGoal_<ContainerAllocator> >::stream(s, indent + "  ", v.goal);
  }
};

} // namespace message_operations
} // namespace ros

#endif // GRIPPER_ACTION_MESSAGE_GRIPPERMOVEACTIONGOAL_H
