// Generated by gencpp from file gripper_action/gripperMoveFeedback.msg
// DO NOT EDIT!


#ifndef GRIPPER_ACTION_MESSAGE_GRIPPERMOVEFEEDBACK_H
#define GRIPPER_ACTION_MESSAGE_GRIPPERMOVEFEEDBACK_H


#include <string>
#include <vector>
#include <memory>

#include <ros/types.h>
#include <ros/serialization.h>
#include <ros/builtin_message_traits.h>
#include <ros/message_operations.h>


namespace gripper_action
{
template <class ContainerAllocator>
struct gripperMoveFeedback_
{
  typedef gripperMoveFeedback_<ContainerAllocator> Type;

  gripperMoveFeedback_()
    {
    }
  gripperMoveFeedback_(const ContainerAllocator& _alloc)
    {
  (void)_alloc;
    }







  typedef boost::shared_ptr< ::gripper_action::gripperMoveFeedback_<ContainerAllocator> > Ptr;
  typedef boost::shared_ptr< ::gripper_action::gripperMoveFeedback_<ContainerAllocator> const> ConstPtr;

}; // struct gripperMoveFeedback_

typedef ::gripper_action::gripperMoveFeedback_<std::allocator<void> > gripperMoveFeedback;

typedef boost::shared_ptr< ::gripper_action::gripperMoveFeedback > gripperMoveFeedbackPtr;
typedef boost::shared_ptr< ::gripper_action::gripperMoveFeedback const> gripperMoveFeedbackConstPtr;

// constants requiring out of line definition



template<typename ContainerAllocator>
std::ostream& operator<<(std::ostream& s, const ::gripper_action::gripperMoveFeedback_<ContainerAllocator> & v)
{
ros::message_operations::Printer< ::gripper_action::gripperMoveFeedback_<ContainerAllocator> >::stream(s, "", v);
return s;
}


} // namespace gripper_action

namespace ros
{
namespace message_traits
{





template <class ContainerAllocator>
struct IsMessage< ::gripper_action::gripperMoveFeedback_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsMessage< ::gripper_action::gripperMoveFeedback_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct IsFixedSize< ::gripper_action::gripperMoveFeedback_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsFixedSize< ::gripper_action::gripperMoveFeedback_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct HasHeader< ::gripper_action::gripperMoveFeedback_<ContainerAllocator> >
  : FalseType
  { };

template <class ContainerAllocator>
struct HasHeader< ::gripper_action::gripperMoveFeedback_<ContainerAllocator> const>
  : FalseType
  { };


template<class ContainerAllocator>
struct MD5Sum< ::gripper_action::gripperMoveFeedback_<ContainerAllocator> >
{
  static const char* value()
  {
    return "d41d8cd98f00b204e9800998ecf8427e";
  }

  static const char* value(const ::gripper_action::gripperMoveFeedback_<ContainerAllocator>&) { return value(); }
  static const uint64_t static_value1 = 0xd41d8cd98f00b204ULL;
  static const uint64_t static_value2 = 0xe9800998ecf8427eULL;
};

template<class ContainerAllocator>
struct DataType< ::gripper_action::gripperMoveFeedback_<ContainerAllocator> >
{
  static const char* value()
  {
    return "gripper_action/gripperMoveFeedback";
  }

  static const char* value(const ::gripper_action::gripperMoveFeedback_<ContainerAllocator>&) { return value(); }
};

template<class ContainerAllocator>
struct Definition< ::gripper_action::gripperMoveFeedback_<ContainerAllocator> >
{
  static const char* value()
  {
    return "# ====== DO NOT MODIFY! AUTOGENERATED FROM AN ACTION DEFINITION ======\n"
"\n"
;
  }

  static const char* value(const ::gripper_action::gripperMoveFeedback_<ContainerAllocator>&) { return value(); }
};

} // namespace message_traits
} // namespace ros

namespace ros
{
namespace serialization
{

  template<class ContainerAllocator> struct Serializer< ::gripper_action::gripperMoveFeedback_<ContainerAllocator> >
  {
    template<typename Stream, typename T> inline static void allInOne(Stream&, T)
    {}

    ROS_DECLARE_ALLINONE_SERIALIZER
  }; // struct gripperMoveFeedback_

} // namespace serialization
} // namespace ros

namespace ros
{
namespace message_operations
{

template<class ContainerAllocator>
struct Printer< ::gripper_action::gripperMoveFeedback_<ContainerAllocator> >
{
  template<typename Stream> static void stream(Stream&, const std::string&, const ::gripper_action::gripperMoveFeedback_<ContainerAllocator>&)
  {}
};

} // namespace message_operations
} // namespace ros

#endif // GRIPPER_ACTION_MESSAGE_GRIPPERMOVEFEEDBACK_H
