(cl:defpackage onrobot_gripper_msgs-msg
  (:use )
  (:export
   "<JOINTCONTROLLERSTATE>"
   "JOINTCONTROLLERSTATE"
   "<ONROBOTGRIPPERCOMMAND>"
   "ONROBOTGRIPPERCOMMAND"
   "<ONROBOTGRIPPERCOMMANDACTION>"
   "ONROBOTGRIPPERCOMMANDACTION"
   "<ONROBOTGRIPPERCOMMANDACTIONFEEDBACK>"
   "ONROBOTGRIPPERCOMMANDACTIONFEEDBACK"
   "<ONROBOTGRIPPERCOMMANDACTIONGOAL>"
   "ONROBOTGRIPPERCOMMANDACTIONGOAL"
   "<ONROBOTGRIPPERCOMMANDACTIONRESULT>"
   "ONROBOTGRIPPERCOMMANDACTIONRESULT"
   "<ONROBOTGRIPPERCOMMANDFEEDBACK>"
   "ONROBOTGRIPPERCOMMANDFEEDBACK"
   "<ONROBOTGRIPPERCOMMANDGOAL>"
   "ONROBOTGRIPPERCOMMANDGOAL"
   "<ONROBOTGRIPPERCOMMANDRESULT>"
   "ONROBOTGRIPPERCOMMANDRESULT"
  ))

