; Auto-generated. Do not edit!


(cl:in-package onrobot_gripper_msgs-msg)


;//! \htmlinclude OnrobotGripperCommandGoal.msg.html

(cl:defclass <OnrobotGripperCommandGoal> (roslisp-msg-protocol:ros-message)
  ((command
    :reader command
    :initarg :command
    :type onrobot_gripper_msgs-msg:OnrobotGripperCommand
    :initform (cl:make-instance 'onrobot_gripper_msgs-msg:OnrobotGripperCommand)))
)

(cl:defclass OnrobotGripperCommandGoal (<OnrobotGripperCommandGoal>)
  ())

(cl:defmethod cl:initialize-instance :after ((m <OnrobotGripperCommandGoal>) cl:&rest args)
  (cl:declare (cl:ignorable args))
  (cl:unless (cl:typep m 'OnrobotGripperCommandGoal)
    (roslisp-msg-protocol:msg-deprecation-warning "using old message class name onrobot_gripper_msgs-msg:<OnrobotGripperCommandGoal> is deprecated: use onrobot_gripper_msgs-msg:OnrobotGripperCommandGoal instead.")))

(cl:ensure-generic-function 'command-val :lambda-list '(m))
(cl:defmethod command-val ((m <OnrobotGripperCommandGoal>))
  (roslisp-msg-protocol:msg-deprecation-warning "Using old-style slot reader onrobot_gripper_msgs-msg:command-val is deprecated.  Use onrobot_gripper_msgs-msg:command instead.")
  (command m))
(cl:defmethod roslisp-msg-protocol:serialize ((msg <OnrobotGripperCommandGoal>) ostream)
  "Serializes a message object of type '<OnrobotGripperCommandGoal>"
  (roslisp-msg-protocol:serialize (cl:slot-value msg 'command) ostream)
)
(cl:defmethod roslisp-msg-protocol:deserialize ((msg <OnrobotGripperCommandGoal>) istream)
  "Deserializes a message object of type '<OnrobotGripperCommandGoal>"
  (roslisp-msg-protocol:deserialize (cl:slot-value msg 'command) istream)
  msg
)
(cl:defmethod roslisp-msg-protocol:ros-datatype ((msg (cl:eql '<OnrobotGripperCommandGoal>)))
  "Returns string type for a message object of type '<OnrobotGripperCommandGoal>"
  "onrobot_gripper_msgs/OnrobotGripperCommandGoal")
(cl:defmethod roslisp-msg-protocol:ros-datatype ((msg (cl:eql 'OnrobotGripperCommandGoal)))
  "Returns string type for a message object of type 'OnrobotGripperCommandGoal"
  "onrobot_gripper_msgs/OnrobotGripperCommandGoal")
(cl:defmethod roslisp-msg-protocol:md5sum ((type (cl:eql '<OnrobotGripperCommandGoal>)))
  "Returns md5sum for a message object of type '<OnrobotGripperCommandGoal>"
  "86fd82f4ddc48a4cb6856cfa69217e43")
(cl:defmethod roslisp-msg-protocol:md5sum ((type (cl:eql 'OnrobotGripperCommandGoal)))
  "Returns md5sum for a message object of type 'OnrobotGripperCommandGoal"
  "86fd82f4ddc48a4cb6856cfa69217e43")
(cl:defmethod roslisp-msg-protocol:message-definition ((type (cl:eql '<OnrobotGripperCommandGoal>)))
  "Returns full string definition for message of type '<OnrobotGripperCommandGoal>"
  (cl:format cl:nil "# ====== DO NOT MODIFY! AUTOGENERATED FROM AN ACTION DEFINITION ======~%onrobot_gripper_msgs/OnrobotGripperCommand command~%~%================================================================================~%MSG: onrobot_gripper_msgs/OnrobotGripperCommand~%float64 position~%float64 max_effort~%~%~%"))
(cl:defmethod roslisp-msg-protocol:message-definition ((type (cl:eql 'OnrobotGripperCommandGoal)))
  "Returns full string definition for message of type 'OnrobotGripperCommandGoal"
  (cl:format cl:nil "# ====== DO NOT MODIFY! AUTOGENERATED FROM AN ACTION DEFINITION ======~%onrobot_gripper_msgs/OnrobotGripperCommand command~%~%================================================================================~%MSG: onrobot_gripper_msgs/OnrobotGripperCommand~%float64 position~%float64 max_effort~%~%~%"))
(cl:defmethod roslisp-msg-protocol:serialization-length ((msg <OnrobotGripperCommandGoal>))
  (cl:+ 0
     (roslisp-msg-protocol:serialization-length (cl:slot-value msg 'command))
))
(cl:defmethod roslisp-msg-protocol:ros-message-to-list ((msg <OnrobotGripperCommandGoal>))
  "Converts a ROS message object to a list"
  (cl:list 'OnrobotGripperCommandGoal
    (cl:cons ':command (command msg))
))
