(cl:defpackage gripper_action-msg
  (:use )
  (:export
   "<GRIPPERGOAL>"
   "GRIPPERGOAL"
   "<GRIPPERMOVEACTION>"
   "GRIPPERMOVEACTION"
   "<GRIPPERMOVEACTIONFEEDBACK>"
   "GRIPPERMOVEACTIONFEEDBACK"
   "<GRIPPERMOVEACTIONGOAL>"
   "GRIPPERMOVEACTIONGOAL"
   "<GRIPPERMOVEACTIONRESULT>"
   "GRIPPERMOVEACTIONRESULT"
   "<GRIPPERMOVEFEEDBACK>"
   "GRIPPERMOVEFEEDBACK"
   "<GRIPPERMOVEGOAL>"
   "GRIPPERMOVEGOAL"
   "<GRIPPERMOVERESULT>"
   "GRIPPERMOVERESULT"
  ))

