; Auto-generated. Do not edit!


(cl:in-package gripper_action-msg)


;//! \htmlinclude gripperMoveFeedback.msg.html

(cl:defclass <gripperMoveFeedback> (roslisp-msg-protocol:ros-message)
  ()
)

(cl:defclass gripperMoveFeedback (<gripperMoveFeedback>)
  ())

(cl:defmethod cl:initialize-instance :after ((m <gripperMoveFeedback>) cl:&rest args)
  (cl:declare (cl:ignorable args))
  (cl:unless (cl:typep m 'gripperMoveFeedback)
    (roslisp-msg-protocol:msg-deprecation-warning "using old message class name gripper_action-msg:<gripperMoveFeedback> is deprecated: use gripper_action-msg:gripperMoveFeedback instead.")))
(cl:defmethod roslisp-msg-protocol:serialize ((msg <gripperMoveFeedback>) ostream)
  "Serializes a message object of type '<gripperMoveFeedback>"
)
(cl:defmethod roslisp-msg-protocol:deserialize ((msg <gripperMoveFeedback>) istream)
  "Deserializes a message object of type '<gripperMoveFeedback>"
  msg
)
(cl:defmethod roslisp-msg-protocol:ros-datatype ((msg (cl:eql '<gripperMoveFeedback>)))
  "Returns string type for a message object of type '<gripperMoveFeedback>"
  "gripper_action/gripperMoveFeedback")
(cl:defmethod roslisp-msg-protocol:ros-datatype ((msg (cl:eql 'gripperMoveFeedback)))
  "Returns string type for a message object of type 'gripperMoveFeedback"
  "gripper_action/gripperMoveFeedback")
(cl:defmethod roslisp-msg-protocol:md5sum ((type (cl:eql '<gripperMoveFeedback>)))
  "Returns md5sum for a message object of type '<gripperMoveFeedback>"
  "d41d8cd98f00b204e9800998ecf8427e")
(cl:defmethod roslisp-msg-protocol:md5sum ((type (cl:eql 'gripperMoveFeedback)))
  "Returns md5sum for a message object of type 'gripperMoveFeedback"
  "d41d8cd98f00b204e9800998ecf8427e")
(cl:defmethod roslisp-msg-protocol:message-definition ((type (cl:eql '<gripperMoveFeedback>)))
  "Returns full string definition for message of type '<gripperMoveFeedback>"
  (cl:format cl:nil "# ====== DO NOT MODIFY! AUTOGENERATED FROM AN ACTION DEFINITION ======~%~%~%~%"))
(cl:defmethod roslisp-msg-protocol:message-definition ((type (cl:eql 'gripperMoveFeedback)))
  "Returns full string definition for message of type 'gripperMoveFeedback"
  (cl:format cl:nil "# ====== DO NOT MODIFY! AUTOGENERATED FROM AN ACTION DEFINITION ======~%~%~%~%"))
(cl:defmethod roslisp-msg-protocol:serialization-length ((msg <gripperMoveFeedback>))
  (cl:+ 0
))
(cl:defmethod roslisp-msg-protocol:ros-message-to-list ((msg <gripperMoveFeedback>))
  "Converts a ROS message object to a list"
  (cl:list 'gripperMoveFeedback
))
