; Auto-generated. Do not edit!


(cl:in-package gripper_action-msg)


;//! \htmlinclude gripperMoveResult.msg.html

(cl:defclass <gripperMoveResult> (roslisp-msg-protocol:ros-message)
  ((success
    :reader success
    :initarg :success
    :type cl:boolean
    :initform cl:nil)
   (failed
    :reader failed
    :initarg :failed
    :type cl:boolean
    :initform cl:nil)
   (error
    :reader error
    :initarg :error
    :type cl:boolean
    :initform cl:nil))
)

(cl:defclass gripperMoveResult (<gripperMoveResult>)
  ())

(cl:defmethod cl:initialize-instance :after ((m <gripperMoveResult>) cl:&rest args)
  (cl:declare (cl:ignorable args))
  (cl:unless (cl:typep m 'gripperMoveResult)
    (roslisp-msg-protocol:msg-deprecation-warning "using old message class name gripper_action-msg:<gripperMoveResult> is deprecated: use gripper_action-msg:gripperMoveResult instead.")))

(cl:ensure-generic-function 'success-val :lambda-list '(m))
(cl:defmethod success-val ((m <gripperMoveResult>))
  (roslisp-msg-protocol:msg-deprecation-warning "Using old-style slot reader gripper_action-msg:success-val is deprecated.  Use gripper_action-msg:success instead.")
  (success m))

(cl:ensure-generic-function 'failed-val :lambda-list '(m))
(cl:defmethod failed-val ((m <gripperMoveResult>))
  (roslisp-msg-protocol:msg-deprecation-warning "Using old-style slot reader gripper_action-msg:failed-val is deprecated.  Use gripper_action-msg:failed instead.")
  (failed m))

(cl:ensure-generic-function 'error-val :lambda-list '(m))
(cl:defmethod error-val ((m <gripperMoveResult>))
  (roslisp-msg-protocol:msg-deprecation-warning "Using old-style slot reader gripper_action-msg:error-val is deprecated.  Use gripper_action-msg:error instead.")
  (error m))
(cl:defmethod roslisp-msg-protocol:serialize ((msg <gripperMoveResult>) ostream)
  "Serializes a message object of type '<gripperMoveResult>"
  (cl:write-byte (cl:ldb (cl:byte 8 0) (cl:if (cl:slot-value msg 'success) 1 0)) ostream)
  (cl:write-byte (cl:ldb (cl:byte 8 0) (cl:if (cl:slot-value msg 'failed) 1 0)) ostream)
  (cl:write-byte (cl:ldb (cl:byte 8 0) (cl:if (cl:slot-value msg 'error) 1 0)) ostream)
)
(cl:defmethod roslisp-msg-protocol:deserialize ((msg <gripperMoveResult>) istream)
  "Deserializes a message object of type '<gripperMoveResult>"
    (cl:setf (cl:slot-value msg 'success) (cl:not (cl:zerop (cl:read-byte istream))))
    (cl:setf (cl:slot-value msg 'failed) (cl:not (cl:zerop (cl:read-byte istream))))
    (cl:setf (cl:slot-value msg 'error) (cl:not (cl:zerop (cl:read-byte istream))))
  msg
)
(cl:defmethod roslisp-msg-protocol:ros-datatype ((msg (cl:eql '<gripperMoveResult>)))
  "Returns string type for a message object of type '<gripperMoveResult>"
  "gripper_action/gripperMoveResult")
(cl:defmethod roslisp-msg-protocol:ros-datatype ((msg (cl:eql 'gripperMoveResult)))
  "Returns string type for a message object of type 'gripperMoveResult"
  "gripper_action/gripperMoveResult")
(cl:defmethod roslisp-msg-protocol:md5sum ((type (cl:eql '<gripperMoveResult>)))
  "Returns md5sum for a message object of type '<gripperMoveResult>"
  "86a42cb736fc6aa448ba78030c84689c")
(cl:defmethod roslisp-msg-protocol:md5sum ((type (cl:eql 'gripperMoveResult)))
  "Returns md5sum for a message object of type 'gripperMoveResult"
  "86a42cb736fc6aa448ba78030c84689c")
(cl:defmethod roslisp-msg-protocol:message-definition ((type (cl:eql '<gripperMoveResult>)))
  "Returns full string definition for message of type '<gripperMoveResult>"
  (cl:format cl:nil "# ====== DO NOT MODIFY! AUTOGENERATED FROM AN ACTION DEFINITION ======~%bool success~%bool failed~%bool error~%~%~%"))
(cl:defmethod roslisp-msg-protocol:message-definition ((type (cl:eql 'gripperMoveResult)))
  "Returns full string definition for message of type 'gripperMoveResult"
  (cl:format cl:nil "# ====== DO NOT MODIFY! AUTOGENERATED FROM AN ACTION DEFINITION ======~%bool success~%bool failed~%bool error~%~%~%"))
(cl:defmethod roslisp-msg-protocol:serialization-length ((msg <gripperMoveResult>))
  (cl:+ 0
     1
     1
     1
))
(cl:defmethod roslisp-msg-protocol:ros-message-to-list ((msg <gripperMoveResult>))
  "Converts a ROS message object to a list"
  (cl:list 'gripperMoveResult
    (cl:cons ':success (success msg))
    (cl:cons ':failed (failed msg))
    (cl:cons ':error (error msg))
))
