// Generated by gencpp from file onrobot_gripper_msgs/OnrobotGripperCommandGoal.msg
// DO NOT EDIT!


#ifndef ONROBOT_GRIPPER_MSGS_MESSAGE_ONROBOTGRIPPERCOMMANDGOAL_H
#define ONROBOT_GRIPPER_MSGS_MESSAGE_ONROBOTGRIPPERCOMMANDGOAL_H


#include <string>
#include <vector>
#include <memory>

#include <ros/types.h>
#include <ros/serialization.h>
#include <ros/builtin_message_traits.h>
#include <ros/message_operations.h>

#include <onrobot_gripper_msgs/OnrobotGripperCommand.h>

namespace onrobot_gripper_msgs
{
template <class ContainerAllocator>
struct OnrobotGripperCommandGoal_
{
  typedef OnrobotGripperCommandGoal_<ContainerAllocator> Type;

  OnrobotGripperCommandGoal_()
    : command()  {
    }
  OnrobotGripperCommandGoal_(const ContainerAllocator& _alloc)
    : command(_alloc)  {
  (void)_alloc;
    }



   typedef  ::onrobot_gripper_msgs::OnrobotGripperCommand_<ContainerAllocator>  _command_type;
  _command_type command;





  typedef boost::shared_ptr< ::onrobot_gripper_msgs::OnrobotGripperCommandGoal_<ContainerAllocator> > Ptr;
  typedef boost::shared_ptr< ::onrobot_gripper_msgs::OnrobotGripperCommandGoal_<ContainerAllocator> const> ConstPtr;

}; // struct OnrobotGripperCommandGoal_

typedef ::onrobot_gripper_msgs::OnrobotGripperCommandGoal_<std::allocator<void> > OnrobotGripperCommandGoal;

typedef boost::shared_ptr< ::onrobot_gripper_msgs::OnrobotGripperCommandGoal > OnrobotGripperCommandGoalPtr;
typedef boost::shared_ptr< ::onrobot_gripper_msgs::OnrobotGripperCommandGoal const> OnrobotGripperCommandGoalConstPtr;

// constants requiring out of line definition



template<typename ContainerAllocator>
std::ostream& operator<<(std::ostream& s, const ::onrobot_gripper_msgs::OnrobotGripperCommandGoal_<ContainerAllocator> & v)
{
ros::message_operations::Printer< ::onrobot_gripper_msgs::OnrobotGripperCommandGoal_<ContainerAllocator> >::stream(s, "", v);
return s;
}


template<typename ContainerAllocator1, typename ContainerAllocator2>
bool operator==(const ::onrobot_gripper_msgs::OnrobotGripperCommandGoal_<ContainerAllocator1> & lhs, const ::onrobot_gripper_msgs::OnrobotGripperCommandGoal_<ContainerAllocator2> & rhs)
{
  return lhs.command == rhs.command;
}

template<typename ContainerAllocator1, typename ContainerAllocator2>
bool operator!=(const ::onrobot_gripper_msgs::OnrobotGripperCommandGoal_<ContainerAllocator1> & lhs, const ::onrobot_gripper_msgs::OnrobotGripperCommandGoal_<ContainerAllocator2> & rhs)
{
  return !(lhs == rhs);
}


} // namespace onrobot_gripper_msgs

namespace ros
{
namespace message_traits
{





template <class ContainerAllocator>
struct IsMessage< ::onrobot_gripper_msgs::OnrobotGripperCommandGoal_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsMessage< ::onrobot_gripper_msgs::OnrobotGripperCommandGoal_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct IsFixedSize< ::onrobot_gripper_msgs::OnrobotGripperCommandGoal_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsFixedSize< ::onrobot_gripper_msgs::OnrobotGripperCommandGoal_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct HasHeader< ::onrobot_gripper_msgs::OnrobotGripperCommandGoal_<ContainerAllocator> >
  : FalseType
  { };

template <class ContainerAllocator>
struct HasHeader< ::onrobot_gripper_msgs::OnrobotGripperCommandGoal_<ContainerAllocator> const>
  : FalseType
  { };


template<class ContainerAllocator>
struct MD5Sum< ::onrobot_gripper_msgs::OnrobotGripperCommandGoal_<ContainerAllocator> >
{
  static const char* value()
  {
    return "86fd82f4ddc48a4cb6856cfa69217e43";
  }

  static const char* value(const ::onrobot_gripper_msgs::OnrobotGripperCommandGoal_<ContainerAllocator>&) { return value(); }
  static const uint64_t static_value1 = 0x86fd82f4ddc48a4cULL;
  static const uint64_t static_value2 = 0xb6856cfa69217e43ULL;
};

template<class ContainerAllocator>
struct DataType< ::onrobot_gripper_msgs::OnrobotGripperCommandGoal_<ContainerAllocator> >
{
  static const char* value()
  {
    return "onrobot_gripper_msgs/OnrobotGripperCommandGoal";
  }

  static const char* value(const ::onrobot_gripper_msgs::OnrobotGripperCommandGoal_<ContainerAllocator>&) { return value(); }
};

template<class ContainerAllocator>
struct Definition< ::onrobot_gripper_msgs::OnrobotGripperCommandGoal_<ContainerAllocator> >
{
  static const char* value()
  {
    return "# ====== DO NOT MODIFY! AUTOGENERATED FROM AN ACTION DEFINITION ======\n"
"onrobot_gripper_msgs/OnrobotGripperCommand command\n"
"\n"
"================================================================================\n"
"MSG: onrobot_gripper_msgs/OnrobotGripperCommand\n"
"float64 position\n"
"float64 max_effort\n"
;
  }

  static const char* value(const ::onrobot_gripper_msgs::OnrobotGripperCommandGoal_<ContainerAllocator>&) { return value(); }
};

} // namespace message_traits
} // namespace ros

namespace ros
{
namespace serialization
{

  template<class ContainerAllocator> struct Serializer< ::onrobot_gripper_msgs::OnrobotGripperCommandGoal_<ContainerAllocator> >
  {
    template<typename Stream, typename T> inline static void allInOne(Stream& stream, T m)
    {
      stream.next(m.command);
    }

    ROS_DECLARE_ALLINONE_SERIALIZER
  }; // struct OnrobotGripperCommandGoal_

} // namespace serialization
} // namespace ros

namespace ros
{
namespace message_operations
{

template<class ContainerAllocator>
struct Printer< ::onrobot_gripper_msgs::OnrobotGripperCommandGoal_<ContainerAllocator> >
{
  template<typename Stream> static void stream(Stream& s, const std::string& indent, const ::onrobot_gripper_msgs::OnrobotGripperCommandGoal_<ContainerAllocator>& v)
  {
    s << indent << "command: ";
    s << std::endl;
    Printer< ::onrobot_gripper_msgs::OnrobotGripperCommand_<ContainerAllocator> >::stream(s, indent + "  ", v.command);
  }
};

} // namespace message_operations
} // namespace ros

#endif // ONROBOT_GRIPPER_MSGS_MESSAGE_ONROBOTGRIPPERCOMMANDGOAL_H
